---
- name: update homebrew
  community.general.homebrew:
    update_homebrew: true

- name: install homebrew packages
  community.general.homebrew:
    name:
      - anyenv
      - fd
      - ffmpeg
      - fzf
      - gh
      - imagemagick
      - jq
      - ncdu
      - tree
      - wget
      - yarn
      - zlib