---
- name: AppleShowAllFiles
  community.general.osx_defaults:
    domain: com.apple.finder
    key: AppleShowAllFiles
    type: bool
    value: TRUE


- name: AppleShowAllExtensions
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: AppleShowAllExtensions
    type: bool
    value: TRUE


- name: AppleTakeScreenshot
  community.general.osx_defaults:
    domain: com.apple.screencapture
    key: location
    type: string
    value: ~/Desktop/screenshots


- name: AppleShowBatteryPercentage
  community.general.osx_defaults:
    domain: com.apple.menuextra.battery
    key: ShowPercent
    type: string
    value: YES